services:
  humanresourcesapi:
    container_name: humanresourcesapi

  deamonnotification:
    container_name: deamonnotification

  distributedcache:
    image: redis

  seq:
    image: datalust/seq:latest

  portainer:
    image: portainer/portainer-ce

  messagebus:
    image: rabbitmq:management

  qdrant:
    image: qdrant/qdrant:latest

  ollama:
    image: ollama/ollama:latest