apiVersion: v1
kind: Service
metadata:
  name: humanresources-api-service
spec:
  selector:
    app: humanresources-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP